language: node_js

node_js:
  # - "8"
  - "lts/*"
  - "node"

addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i

scripts:
  - cat karma.conf.js
  - npm run lint
  - npm run test -- --single-run

notifications:
  slack:
    rooms:
      # obtained by running
      # docker run -v $(pwd):/home/travis ruby sh -c 'set -xe; cd /home/travis; gem install travis -v 1.8.8 --no-rdoc --no-ri; travis encrypt "<account>:<token>#channel" --add notifications.slack.rooms'
      # - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg="
      # or
      # - <account>:<token>#channel
      - secure: oFCH3KX5jOKBGgm6jtDdX0/d0DflzDcdUE5UN/oQvkUzImVDX708BRSWWZ+TfQIuxOhKPjlaAojKHpCJ2uPoISIEMgljIZXNWIgXq0NoShSWiNuudHByCHEdG7mg9iyTZxTTe0I8FLCtx6opbo+9doe/ZWVjpTzRNJSa/tpSjCwk799NesnZhkxF8SwUTAL1fldbRhQnMt2Yiyr5e8TNk7hG/BDcSTpRrauIPRnC7hgKFSL5EV3klqJQgdOt8LuJ+T9eVIBB3OWiI/pD3FNk2JS43qvMvMTiTa09f/Cx5XrEftp5EpvuXB9lqm5F0O54oOYDHLK+em83klE7aAy+jUouaKQu2DjjHhZsdj4uUvX2aHNmLNMVORNVSJ4gZybUcjGP+2wDv0DLyBrH1hECp67qljR+/N/eogWvtXM4MynrjdLvkLRGoFsF9kkWmQyWOFvW3o8lQy8im+aQDNXR91C0VcdshNi9N5bK2W8x9Exd12vTrCOztBYzi/NBDrQoitR9AuIS25YGzuCBp1XaR+eRS2+Qr67oy1MfuJwyGAxd1WLyqXgrxQ6gi6XELnqCqtyKsGib0gDaEmsmV4YHklmah2aX9Z41Du9Bm8BykZgfhmfnT8PxCG5oPAiPMd7uB8HR18x9AoCrLB7XCSoiiAgu31ShRuX5ByKdv3Gj0mk=
    on_success: always
    on_failure: always
  # email:
  #   recipients:
  #     - amaranth@itmediaconnect.ro
  #   on_success: never # default: change
  #   on_failure: always # default: always